version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/app/database
    environment:
      - DATABASE_URL=sqlite:///./app/database/app.db
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - APP_URL=${APP_URL}
    command: >
      sh -c "python migrate_db.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  sqlite_data:
    driver: local 