services:
  app:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - .:/app
      - sqlite_data:/app/app/database
    environment:
      - DATABASE_URL=sqlite:///./app/database/app.db
    command: >
      sh -c "python migrate_db.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 9090 --reload"

volumes:
  sqlite_data:
    driver: local

