"""remove user_id from basic_data_logs

Revision ID: 345cbf83ee90
Revises: 6c07117872af
Create Date: 2025-06-07 10:35:31.631253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345cbf83ee90'
down_revision = '6c07117872af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_data_logs') as batch_op:
        batch_op.drop_constraint('fk_basic_data_logs_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_data_logs') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_basic_data_logs_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ### 