"""remove relationship basic_data_logs from user model

Revision ID: 3d1d2601d824
Revises: 345cbf83ee90
Create Date: 2025-06-07 10:38:30.171628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1d2601d824'
down_revision = '345cbf83ee90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 